import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    REACT_APP_FAQ_FLOW_GRAPHQL_MAIN_URL:
      process.env.REACT_APP_FAQ_FLOW_GRAPHQL_MAIN_URL,
    REACT_APP_FAQ_FLOW_AUTHORITYL: process.env.REACT_APP_FAQ_FLOW_AUTHORITYL,
    REACT_APP_FAQ_FLOW_X_API_KEY: process.env.REACT_APP_FAQ_FLOW_X_API_KEY,
    REACT_APP_FAQ_FLOW_USER_AGENT: process.env.REACT_APP_FAQ_FLOW_USER_AGENT,
    REACT_APP_DOCTORS_FLOW_SIGNUP_USERPOOLID:
      process.env.REACT_APP_DOCTORS_FLOW_SIGNUP_USERPOOLID,
    REACT_APP_DOCTORS_FLOW_SIGNUP_CLIENTID:
      process.env.REACT_APP_DOCTORS_FLOW_SIGNUP_CLIENTID,
    REACT_APP_GOOGLE_REDIRECT_SIGNIN_PATH:
      process.env.REACT_APP_GOOGLE_REDIRECT_SIGNIN_PATH,
    REACT_APP_GOOGLE_REDIRECT_SIGNOUT_PATH:
      process.env.REACT_APP_GOOGLE_REDIRECT_SIGNOUT_PATH,
    REACT_APP_COGNITO_CUSTOM_DOMAIN:
      process.env.REACT_APP_COGNITO_CUSTOM_DOMAIN,
    REACT_APP_DOCTORS_FLOW_GRAPHQL_MAIN_URL:
      process.env.REACT_APP_DOCTORS_FLOW_GRAPHQL_MAIN_URL,
    REACT_APP_DOCTORS_FLOW_AUTHORITYL:
      process.env.REACT_APP_DOCTORS_FLOW_AUTHORITYL,
    REACT_APP_HOSPITAL_FLOW_SIGNUP_USERPOOLID:
      process.env.REACT_APP_HOSPITAL_FLOW_SIGNUP_USERPOOLID,
    REACT_APP_HOSPITAL_FLOW_SIGNUP_CLIENTID:
      process.env.REACT_APP_HOSPITAL_FLOW_SIGNUP_CLIENTID,
    REACT_APP_HOSPITAL_FLOW_GRAPHQL_MAIN_URL:
      process.env.REACT_APP_HOSPITAL_FLOW_GRAPHQL_MAIN_URL,
  },
  /* config options here */
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'staged-medlink-files.s3.ap-south-1.amazonaws.com',

      },
    ],
  },
};

export default nextConfig;
