
import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "@/theme";
import StoreProvider from "./StoreProvider";
import { ReduxProvider } from "@/redux/Provider";
import SnackbarComponent from "@/components/commonComponents/SnackbarComponent";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Medlink Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ThemeProvider theme={theme}>
            <AppRouterCacheProvider>
             <ReduxProvider>{children}
              <SnackbarComponent />
             </ReduxProvider>    
            </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
